export enum Szempont {
  Kod = 1,
  Nev = 2,
  Megnevezes = 3,
  Bizonylatszam = 4,
  Ugyfel = 5,
  Keletkezett = 6,
  Null = 7,
  Megrendelve = 8,
  Kivitelezve = 9,
  Keszrejelentve = 10,
  UgyfelKod = 11,
  CsakHaJegyzetIs = 12,


  TeljesitesKeltetol = 15,
  TeljesitesKelteig = 16,
  BizonylatszamCsokkenoSorrend = 17, // Nem kell neki értéket adni, elég ha jelen van a listában.
  UgyfelCim = 18,
  TelepitesiCim = 19,
  TeljesitesKelteSorrend = 20,
  AdottNapon = 21,
  Lejart = 22,
  ReszletekIs = 23,
  Minta = 24,
  PenztarBizonylatszam = 25,
  Idopont = 26,
  UgyfelEmail = 27,
    Hirlevel = 28,
  NincsKiszallitva = 29,
  Fut = 30,
  Targy = 31,
  Kuldo = 32,
  Irattipus = 33,

  MuszakiAllapot = 35,
  UgyfelTelefonszam = 36,
  Lista = 37,
  Telepules = 38,
  Email = 39,
  Telefonszam = 40,
  SzerzodesSzam = 41,
  SzuloKod = 42,
  SzamlazasiGyakorisag = 43,
  DatumTol = 44,
  DatumIg = 45,
  SzamlaKelte = 46,
  BizonylatKod = 47,
  NyomtatasTipus = 48,
  Ervenyes = 49,
  Tajolas = 50,
  Termeles = 51,
  Megjegyzes = 52,
  SzuksegesAramerosseg = 53,
  Cim = 54,
  Ugynoknev = 55,
  Ceg = 56,
  Beosztas = 57,
  Egyeblink = 58,
  Ajanlo = 59
}

